namespace Rajavasantha.Api.Domain;
public abstract class Entity { public Guid Id { get; set; }=Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; }=DateTimeOffset.UtcNow; public DateTimeOffset? UpdatedAt { get; set; } public bool IsDeleted { get; set; } }
public sealed class User:Entity { public required string Email {get;set;} public required string PasswordHash {get;set;} public string? FullName {get;set;} public bool IsActive {get;set;}=true; public ICollection<Role> Roles {get;set;}=new List<Role>(); public ICollection<RefreshToken> RefreshTokens {get;set;}=new List<RefreshToken>(); }
public sealed class Role:Entity { public required string Name {get;set;} public ICollection<User> Users {get;set;}=new List<User>(); }
public sealed class RefreshToken:Entity { public Guid UserId {get;set;} public required string TokenHash {get;set;} public DateTimeOffset ExpiresAt {get;set;} public DateTimeOffset? RevokedAt {get;set;} public User User {get;set;}=null!; }
public sealed class Category:Entity { public required string Name {get;set;} public required string Slug {get;set;} public ICollection<Project> Projects {get;set;}=new List<Project>(); }
public sealed class Project:Entity { public Guid CategoryId {get;set;} public required string Title {get;set;} public required string Slug {get;set;} public required string Summary {get;set;} public string? Body {get;set;} public decimal? GoalAmount {get;set;} public decimal RaisedAmount {get;set;} public bool IsPublished {get;set;} public Category Category {get;set;}=null!; }
public sealed class Donation:Entity { public Guid? ProjectId {get;set;} public required string DonorName {get;set;} public required string Email {get;set;} public decimal Amount {get;set;} public required string Currency {get;set;} public required string Provider {get;set;} public required string Status {get;set;} public string? ProviderPaymentId {get;set;} public string? ReceiptNumber {get;set;} public Project? Project {get;set;} }
public sealed class Volunteer:Entity { public required string FullName {get;set;} public required string Email {get;set;} public string? Phone {get;set;} public required string Interest {get;set;} public string Status {get;set;}="Pending"; public string? ResumePath {get;set;} }
public sealed class ContactMessage:Entity { public required string Name {get;set;} public required string Email {get;set;} public required string Message {get;set;} public string Status {get;set;}="New"; }
public sealed class Album:Entity { public required string Name {get;set;} public required string Slug {get;set;} public ICollection<GalleryItem> Items {get;set;}=new List<GalleryItem>(); }
public sealed class GalleryItem:Entity { public Guid? AlbumId {get;set;} public required string ImagePath {get;set;} public string? AltText {get;set;} public Album? Album {get;set;} }
public sealed class ContentItem:Entity { public required string Type {get;set;} public required string Title {get;set;} public required string Slug {get;set;} public string? Summary {get;set;} public string? Body {get;set;} public DateTimeOffset? PublishedAt {get;set;} public bool IsPublished {get;set;} }
public sealed class Testimonial:Entity { public required string Name {get;set;} public required string Quote {get;set;} public string? Role {get;set;} public bool IsPublished {get;set;} }
public sealed class Partner:Entity { public required string Name {get;set;} public string? Website {get;set;} public string? LogoPath {get;set;} }
public sealed class Document:Entity { public required string Name {get;set;} public required string Path {get;set;} public string? MimeType {get;set;} public bool IsPublic {get;set;} }
public sealed class Setting:Entity { public required string Key {get;set;} public required string Value {get;set;} }
public sealed class ImpactStatistic:Entity { public required string Label {get;set;} public long Value {get;set;} public string? Suffix {get;set;} public int SortOrder {get;set;} }
