using System.IdentityModel.Tokens.Jwt; using System.Security.Claims; using System.Security.Cryptography; using System.Text; using System.Threading.RateLimiting; using Microsoft.AspNetCore.Authentication.JwtBearer; using Microsoft.EntityFrameworkCore; using Microsoft.IdentityModel.Tokens; using Rajavasantha.Api.Application; using Rajavasantha.Api.Domain; using Rajavasantha.Api.Infrastructure;
var b=WebApplication.CreateBuilder(args); var cfg=b.Configuration; var key=cfg["Jwt:Key"]??throw new InvalidOperationException("Jwt:Key is required");
b.Services.AddDbContext<AppDbContext>(o=>o.UseSqlServer(cfg.GetConnectionString("SqlServer"))); b.Services.AddScoped(typeof(IRepository<>),typeof(EfRepository<>)); b.Services.AddScoped<IDonationService,DonationService>(); b.Services.AddOpenApi(); b.Services.AddSwaggerGen(); b.Services.AddCors(o=>o.AddPolicy("web",p=>p.WithOrigins(cfg.GetSection("Cors:Origins").Get<string[]>()??[]).AllowAnyHeader().AllowAnyMethod().AllowCredentials())); b.Services.AddRateLimiter(o=>o.AddFixedWindowLimiter("write",x=>{x.PermitLimit=20;x.Window=TimeSpan.FromMinutes(1);x.QueueLimit=0;})); b.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>o.TokenValidationParameters=new(){ValidateIssuer=true,ValidateAudience=true,ValidateLifetime=true,ValidateIssuerSigningKey=true,ValidIssuer=cfg["Jwt:Issuer"],ValidAudience=cfg["Jwt:Audience"],IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),ClockSkew=TimeSpan.FromMinutes(1)}); b.Services.AddAuthorization(o=>o.AddPolicy("Admin",p=>p.RequireRole("Admin")));
var app=b.Build(); app.UseExceptionHandler("/error"); app.UseHttpsRedirection(); app.UseCors("web"); app.UseRateLimiter(); app.UseAuthentication(); app.UseAuthorization(); if(app.Environment.IsDevelopment()){app.MapOpenApi();app.UseSwagger();app.UseSwaggerUI();} app.MapGet("/error",()=>Results.Problem(statusCode:500));
string Access(User u){var c=new List<Claim>{new(JwtRegisteredClaimNames.Sub,u.Id.ToString()),new(JwtRegisteredClaimNames.Email,u.Email)};c.AddRange(u.Roles.Select(r=>new Claim(ClaimTypes.Role,r.Name)));return new JwtSecurityTokenHandler().WriteToken(new JwtSecurityToken(issuer:cfg["Jwt:Issuer"],audience:cfg["Jwt:Audience"],claims:c,expires:DateTime.UtcNow.AddMinutes(15),signingCredentials:new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),SecurityAlgorithms.HmacSha256)));}
app.MapPost("/api/v1/auth/login",async(Login x,AppDbContext db)=>{var u=await db.Users.Include(x=>x.Roles).SingleOrDefaultAsync(u=>u.Email==x.Email.ToLower());if(u is null||!u.IsActive||!BCrypt.Net.BCrypt.Verify(x.Password,u.PasswordHash))return Results.Unauthorized();var raw=Convert.ToBase64String(RandomNumberGenerator.GetBytes(48));db.RefreshTokens.Add(new(){UserId=u.Id,TokenHash=BCrypt.Net.BCrypt.HashPassword(raw),ExpiresAt=DateTimeOffset.UtcNow.AddDays(14)});await db.SaveChangesAsync();return Results.Ok(new{accessToken=Access(u),refreshToken=raw});}).RequireRateLimiting("write");
app.MapPost("/api/v1/contact",async(ContactInput x,AppDbContext db)=>{if(string.IsNullOrWhiteSpace(x.Name)||!System.Net.Mail.MailAddress.TryCreate(x.Email,out _)||x.Message.Length is <10 or >5000)return Results.ValidationProblem(new Dictionary<string,string[]>{{"message",["Provide a valid message (10–5000 characters)."]}});db.ContactMessages.Add(new(){Name=x.Name.Trim(),Email=x.Email.Trim().ToLowerInvariant(),Message=x.Message.Trim()});await db.SaveChangesAsync();return Results.Accepted();}).RequireRateLimiting("write");
app.MapPost("/api/v1/volunteers",async(VolunteerInput x,AppDbContext db)=>{if(string.IsNullOrWhiteSpace(x.FullName)||!System.Net.Mail.MailAddress.TryCreate(x.Email,out _)||string.IsNullOrWhiteSpace(x.Interest))return Results.BadRequest();var v=new Volunteer{FullName=x.FullName.Trim(),Email=x.Email.Trim().ToLowerInvariant(),Phone=x.Phone?.Trim(),Interest=x.Interest.Trim()};db.Volunteers.Add(v);await db.SaveChangesAsync();return Results.Created($"/api/v1/volunteers/{v.Id}",new {v.Id,v.Status});}).RequireRateLimiting("write");
app.MapGet("/api/v1/projects",async(AppDbContext db)=>Results.Ok(await db.Projects.Include(x=>x.Category).Where(x=>x.IsPublished).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Id,x.Title,x.Slug,x.Summary,Category=x.Category.Name,x.GoalAmount,x.RaisedAmount}).ToListAsync()));
app.MapGet("/api/v1/content/{type}",async(string type,AppDbContext db)=>Results.Ok(await db.Content.Where(x=>x.Type==type&&x.IsPublished).OrderByDescending(x=>x.PublishedAt).ToListAsync()));
var admin=app.MapGroup("/api/v1/admin").RequireAuthorization("Admin"); admin.MapGet("/dashboard",async(AppDbContext db)=>Results.Ok(new{donations=await db.Donations.Where(x=>x.Status=="Paid").SumAsync(x=>(decimal?)x.Amount)??0,volunteers=await db.Volunteers.CountAsync(),messages=await db.ContactMessages.CountAsync(x=>x.Status=="New")})); admin.MapPost("/projects",async(Project x,AppDbContext db)=>{db.Projects.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/v1/projects/{x.Id}",x);});
app.Run(); record Login(string Email,string Password); record ContactInput(string Name,string Email,string Message); record VolunteerInput(string FullName,string Email,string? Phone,string Interest);
